import type { Metadata } from "next";
import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

const lora = Lora({
  subsets: ['latin'],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-serif",
})

const dm_sans = DM_Sans({
  subsets: ['latin'],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

   
    <html lang="en" suppressHydrationWarning>
      <body className={`${lora.variable} ${dm_sans.variable} font-sans overflow-x-hidden`}>
        <ThemeProvider>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
     </ClerkProvider>
  );
}
